name: Other issue
description: File another issue
title: "[Other]: "
labels: [""]
projects: ["sep-uob/237"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue!
  - type: textarea
    id: Describe-the-issue
    attributes:
      label: What is this issue for
      description: Use as much detail as possible
      placeholder: Details...
      value: "Issue"
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: What is the issue about?
      multiple: true
      options:
        - Meeting
        - Organisation
        - Documentation
        - Other
  - type: textarea
    id: What-should-be-done
    attributes:
      label:  What needs to be done?
      description: Inform people of what should be done to fix this issue
  # - type: checkboxes
  #   id: terms
  #   attributes:
  #     label: Code of Conduct
  #     description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com). 
  #     options:
  #       - label: I agree to follow this project's Code of Conduct
  #         required: true
