version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
      DB_HOST: db
      DB_USER: general-user
      DB_PASSWORD: MLAI2024
      DB_NAME: MLAIDB
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    container_name: mysql_container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: MLAI2024
      MYSQL_DATABASE: MLAIDB
      MYSQL_USER: general-user
      MYSQL_PASSWORD: MLAI2024
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
