version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: general-user
      DB_PASSWORD: MLAI2024
      DB_NAME: MLAIDB
    depends_on:
      - db
    volumes:
      - ./python-server:/app  # Mount the server code into the container
    command: python server.py  # Run the Python server script

  db:
    image: mysql:8
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: MLAI2024
      MYSQL_DATABASE: MLAIDB
      MYSQL_USER: general-user
      MYSQL_PASSWORD: MLAI2024
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
