# Use the Node.js base image
FROM node:14-slim

# Set the working directory
WORKDIR /usr/src/app

# Copy the WebSocket server code
COPY websocket-server .

# Install Node.js dependencies
RUN npm install

# Expose the WebSocket server port
EXPOSE 8080

# Run the WebSocket server
CMD ["node", "server.js"]
