# Use the Node.js base image
FROM node:14-slim

# Set the working directory
WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y --no-install-recommends \
    apt-transport-https \
    ca-certificates \
    gnupg \
    gcc \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# Copy the WebSocket server code
COPY websocket-server .

# Install Node.js dependencies
RUN rm -rf /usr/src/app/node_modules
RUN npm install

# Expose the WebSocket server port
EXPOSE 8080

# Run the WebSocket server
CMD ["node", "server.js"]
