# Use the Python base image
FROM python:3.9-slim

# Set the working directory
WORKDIR /usr/src/app

# Copy requirements.txt
COPY requirements.txt ./

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the backend code
COPY python-server .

# Expose the backend port
EXPOSE 3000

# Start the backend
CMD ["python", "server.py"]
