name: Build and Deploy
on:
  push:
    branches:
      - dev
      - bug-fix-cd

permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🔧
        run: |
          cd code/frontend/web-app
          npm install && npm install --only=dev
          npm install @quasar/cli
          npx quasar build

      - name: Deploy 🚀
        run: |
          # Set up Git user for the deployment commit
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Navigate to the build folder
          cd code/frontend/web-app/dist/spa

          # Initialize a new Git repository and switch to the gh-pages branch
          git init
          git checkout -b gh-pages

          # Add and commit all built files
          git add .
          git commit -m "Deploy to GitHub Pages"

          # Force push to the gh-pages branch
          git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" gh-pages
