name: Build and Deploy
on:
  push:
    branches:
      - dev
      - bug-fix-cd
      - deploy-to-domain

permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          cd code/frontend/web-app
          npm install && npm install --only=dev
          npm install @quasar/cli
          npx quasar build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: code/frontend/web-app/dist/spa # The folder the action should deploy.

  domain-deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.u3core.com
          username: ai@u3core.com
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ./
