name: Frontend Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: code/frontend/web-app
        run: |
          npm install -D @vitejs/plugin-vue@2
          npm install

      - name: Run frontend tests
        working-directory: code/frontend/web-app
        run: npm run test:unit

      #Upload test results as an artifact
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-test-results
          path: test-results/
