name: Pylint

on:
  push:
    paths:
      - 'code/backend/python-features/**'
      - 'code/backend/python-server/**'
      - '.github/workflows/pylint.yml'
      - 'code/backend/python-server/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r code/backend/requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files 'code/backend/python-features/*.py') --rcfile=.github/workflows/.pylintrc
        pylint $(git ls-files 'code/backend/python-server/*.py') --rcfile=.github/workflows/.pylintrc
        
