name: Run Unit Tests and Lint Files
"on": push

permissions:
  contents: read

jobs:
  unit_test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm --prefix code/frontend/web install
      - name: Run lint tests
        run: |
          npm --prefix code/frontend/web ci
          npm --prefix code/frontend/web run build
          npm --prefix code/frontend/web run test:unit
          npm --prefix code/frontend/web run lint