name: Run Unit Tests and Lint Files
"on": push

permissions:
  contents: read

jobs:
  unit_test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm --prefix code/frontend/web-app install
      - name: Run lint tests
        run: |
          npm --prefix code/frontend/web-app ci
          npm --prefix code/frontend/web-app run build
          npm --prefix code/frontend/web-app run test:unit
          npm --prefix code/frontend/web-app run lint